### ISSUE TITLE
Collaboration with Kilo

### ISSUE THREAD

**Issue by squat** [gravitational/wormhole#12]
Hi Gravitational team,

I just saw on your blog that you announced Wormhole today; that’s very exciting! I wanted to bring to your attention a project I’ve been developing using in production for several months : https://github.com/squat/kilo. Like Wormhole, Kilo is a WireGuard-based network overlay designed for K8s (though abstracted to work on other backends). It sounds like we have a lot of the same goals in mind: secure inter-node communication for insecure clouds or compliance, cross cloud/region clusters etc. Kilo has a lot of features, e.g. cluster analysis with graphviz, configurable network topologies, and even running K8s clusters across clouds. I’d love to talk about possible collaboration with the Wormhole team to make a really great project for the community. Please let me know how to get in touch!

-Lucas

**Comment by knisbet** [comment]
Hi Lucas, thanks for reaching out, I definitely missed the kilo project in my research of other solutions, a quick look through it seems really cool. Please feel free to contact me:
- email: kevin at gravitational dot com
- keybase: knisbet
- Kubernetes slack: kevin
