### ISSUE TITLE
[FEATURE] Custom cni config

### ISSUE THREAD

**Issue by amon-ra** [gravitational/wormhole#19]
Hello. I am trying to integrate your plugin with cillium but I need to do this: 
https://docs.cilium.io/en/stable/gettingstarted/cni-chaining-generic-veth/.
CNI config is created by your daemon and I only have to add the lines:
```
        {
          "type": "cilium-cni"
        }
```
I have looked at the code but I do not see how I can add this lines. Is any post create hook?
Thanks in advice.

**Comment by knisbet** [comment]
@amon-ra Sorry I didn't notice this issue when it was posted.

The cni configuration is currently generated programatically in the following code block. 
https://github.com/gravitational/wormhole/blob/master/pkg/controller/cni.go#L25-L84

Basically, it's just a golang structure with the CNI configuration and fields set from internal configuration, that get's serialized to json and written to the /etc/cni-net.d/wormhole.conflist directory to configure the CNI plugins. It's likely not hard to hack in the cilium-cni plugin there and to rebuild. 

Also, adding a feature flag specific to cilium or to allow arbitrary chained plugins likely isn't all that difficult, just the way the conf object get's generated might need to be rejigged a bit.

**Comment by wadells** [comment]
We're arching the Gravity project, and this repos as part of it.
